openapi: 3.0.0
info:
  title: CLiQQ PAY E-Money API
  description: | 
    This is the API that MUST be implemented by E-Money Issuers to get accepted at 7-Eleven Stores
  version: 1.0.0c

servers:
  - url: https://ISSUER_HOST/api
  
tags:
- name: "charge"
  description: "A charge deducts against an E-money wallet balance"
- name: "reversal"
  description: "A reversal cancels a previous charge and returns the amount to the walet balance"  
  

paths:
  /charge:
    post:
      summary: Create a charge
      description: |
        This endpoint will be called by cliqqpay whenever a Time based One Time Pin(TOTP) 
        from an E-money issuer partner is presented as payment for goods and/or services
      
      
        Issuer partners implementing this API must respond within 8 seconds or be timed out.
        When a transaction is timed out, cliqqpay will resend the transaction 
        with the retry flag set to true and will wait for another 8 seconds.
      
        
        When no response is received, the terminal will time out and will queue a reversal message.
        
      tags: 
      - "charge"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Charge'
      responses: 
        '200':
          description: |
            this result should ony be returned when the transaction is a retry and the transaction has already
            been processed in a previous request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChargeResponse'
        '201':
          description: |
            This result should be returned if and only if:
            - the terminal is valid
            - the location is valid
            - the signature is valid
            - the totp is valid
            - balance deduction was successful
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/ChargeResponse'
        '400':
          $ref: '#/components/responses/InvalidParameters'
        '500':
          $ref: '#/components/responses/DeductionFailed'
  /reversal:
    post:
      summary: Create a reversal
      description: This endpoint will be called by cliqqpay in response to a reversal message from the terminal
      tags: 
      - "reversal"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reversal'
      responses:
        '200':
          description: this result should only be returned when a charge matching the request was not found
        '201':
          description: this result should only be returned when a charge was found and was reversed
        '400':
          $ref: '#/components/responses/InvalidParameters'

components:
  schemas:
    Charge:
      type: object
      properties:
        totp:
          type: string
          description: time based one time pin. cliqq pay will pre-alocate a 4 digit prefix to each e-money partner
          minLength: 18
          maxLength: 21
          example: 910112345678901234
        currency:
          type: string
          minLength: 3
          maxLength: 8
          enum: [php,usd]
          description: the currency of the charge
          example: php
        amount:
          type: number
          format: int
          minimum: 1
          maximum: 500000
          description: amount to deduct multiplied by 100 i.e. 101.23 -> 10123
          example: 10123
        cashier:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the cashier making the charge
          example: jdelacruz
        terminal:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the terminal making the charge
          example: "16601"
        location:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the store making the charge
          example: 166-columbia
        trace:
          type: string
          minLength: 3
          maxLength: 21
          description: terminal generated trace number 
          example: 166012359591
        requestDate:
          type: string
          description: the date at the terminal when the charge was created, format yyyy-MM-dd
          example: "2018-10-01"
        requestTime:
          type: string
          description: the time at the terminal when the charge was created, format hh:mm:ss assumed to be GMT+8
          example: "23:59:59"
        retry:
          type: boolean
          description: |
            cliqqpay will set this to true to signal a retry.
            when this field is set to true, emoney partners should check if the charge 
            has already been processed using the following combination: requestDate, requestTime, location, terminal, trace
            
            if request was already processed, emoney partners should return the previousresults
          example: false
        signature:
          type: string
          format: base
          description: |
            
            To generate the value, concatenate
            - totp
            - currency
            - amount
            - cashier
            - terminal
            - location
            - trace
            - requestDate
            - requestTime
            - retry
            - sharedSecret
            
            then use SHA256 to produce the signature then prepend the string 'sha256-'
          
            given following values:
            
              - totp: 910112345678901200
              - currency: php
              - amount: 10123
              - cashier: jdelacruz
              - terminal: 16601
              - location: 166-columbia
              - trace: 166012359591
              - requestDate: 2018-10-01
              - requestTime: 23:59:59
              - retry: false
              - sharedSecret: a2c36905-c9bb-4ed2-9423-ec170e1eb6c1
            
            the computed signature is:
            sha256-783610D5A85295D355DD32CAA83277F313A5A00A7AD39CD8FC3AFBE03DF6EFC4
          example: sha256-783610D5A85295D355DD32CAA83277F313A5A00A7AD39CD8FC3AFBE03DF6EFC4
      required:  
        - totp
        - currency
        - amount
        - cashier
        - terminal
        - location
        - trace
        - requestDate
        - requestTime
        - retry
        - signature
        
    ChargeResponse:
      type: object
      properties:
        totp:
          type: string
          description: time based one time pin. cliqq pay will pre-alocate a 4 digit prefix to each e-money partner
          minLength: 18
          maxLength: 21
          example: 910112345678901234
        currency:
          type: string
          minLength: 3
          maxLength: 8
          enum: [php,usd]
          description: the currency of the charge
          example: php
        amount:
          type: number
          format: int
          minimum: 1
          maximum: 500000
          description: amount to deduct multiplied by 100 i.e. 101.23 -> 10123
          example: 10123
        cashier:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the cashier making the charge
          example: jdelacruz
        terminal:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the terminal making the charge
          example: "16601"
        location:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the store making the charge
          example: 166-columbia
        trace:
          type: string
          minLength: 3
          maxLength: 21
          description: terminal generated trace number 
          example: 166012359591
        requestDate:
          type: string
          description: the date at the terminal when the charge was created, format yyyy-MM-dd
          example: "2018-10-01"
        requestTime:
          type: string
          description: the time at the terminal when the charge was created, format hh:mm:ss assumed to be GMT+8
          example: "23:59:59"
        retry:
          type: boolean
          description: |
            cliqqpay will set this to true to signal a retry.
            when this field is set to true, emoney partners should check if the charge 
            has already been processed using the following combination: requestDate, requestTime, location, terminal, trace
            
            if request was already processed, emoney partners should return the previousresults
          example: false
        resultCode:
          type: number
          format: int
          description: machine readable status code, 0 for successful, non zero for error
          example: 0
        result:
          type: string
          minLength: 3
          maxLength: 21
          description: human readable status or error message
          example: "charge successful"
        authorizationCode:
          type: string
          minLength: 3
          maxLength: 21
          description: authorization code generated by issuer side system, empty when statusCode is non zero
          example: 123456
        issuerReference:
          type: string
          minLength: 3
          maxLength: 21
          description: reference number of the transaction on the issuer side system
          example: 16601010003
        issuerDate:
          type: string
          description: the date at the issuer side system
          example: "2018-10-02"
        issuerTime:
          type: string
          description: the time at the issuer side system
          example: "01:00:03"
        mobileNumber:
          type: string
          description: the mobile number of the account
          example: "+639175115611"
        remainingBalance:
          type: number
          format: int
          description: the remaining balance of the wallet multiplied by 100 i.e. 101.23 -> 10123          
          example: 10123
        signature:
          type: string
          format: base
          description: |
            
            To generate the value, concatenate
            - totp
            - currency
            - amount
            - cashier
            - terminal
            - location
            - trace
            - requestDate
            - requestTime
            - retry
            - resultCode
            - result
            - authorizationCode
            - issuerReference
            - issuerDate
            - issuerTime
            - sharedSecret
            
            then use SHA256 to produce the signature then prepend the string 'sha256-'
          
            
            given the following values:
            
              - totp: 910112345678901200
              - currency: php
              - amount: 10123
              - cashier: jdelacruz
              - terminal: 16601
              - location: 166-columbia
              - trace: 166012359591
              - requestDate: 2018-10-01
              - requestTime: 23:59:59
              - retry: false
              - resultCode: 0
              - result: charge successful
              - authorizationCode: 123456
              - issuerReference: 16601010003
              - issuerDate: 2018-10-02
              - issuerTime: 01:00:03
              - mobileNumber: +639175115611
              - remainingBalance: 10123
              - sharedSecret: a2c36905-c9bb-4ed2-9423-ec170e1eb6c1
            
            the computed signature is:
            sha256-8B6D0C433876D83098FC568755D2DB222A05B69A84C50FF1263D8563BB45E681
          example: sha256-8B6D0C433876D83098FC568755D2DB222A05B69A84C50FF1263D8563BB45E681
      required:  
        - totp
        - currency
        - amount
        - cashier
        - terminal
        - location
        - trace
        - requestDate
        - requestTime
        - signature
        - retry
        - resultCode
        - result
        - authorizationCode
        - issuerReference
        - issuerDate
        - issuerTime
        
    Reversal:
      type: object
      properties:
        totp:
          type: string
          description: time based one time pin. cliqq pay will pre-alocate a 4 digit prefix to each e-money partner
          minLength: 18
          maxLength: 21
          example: 910112345678901234
        currency:
          type: string
          minLength: 3
          maxLength: 8
          enum: [php,usd]
          description: the currency of the charge being reveresed
          example: php
        amount:
          type: number
          format: int
          minimum: 1
          maximum: 500000
          description: amount deducted by the charge multiplied by 100 i.e. 101.23 -> 10123
          example: 10123
        cashier:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the cashier making the reversal
          example: jdelacruz
        terminal:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the terminal that made the charge being reveresed
          example: "16601"
        location:
          type: string
          minLength: 3
          maxLength: 55
          description: identifies the store making the charge being reveresed
          example: 166-columbia
        trace:
          type: string
          minLength: 3
          maxLength: 21
          description: terminal generated trace number when the charge was created 
          example: 166012359591
        requestDate:
          type: string
          format: date
          description: the date at the terminal when the charge was created
          example: "2018-10-01"
        requestTime:
          type: string
          format: time
          description: the time at the terminal when the charge was created
          example: "23:59:59"
        signature:
          type: string
          format: byte
          description: |
            base64 encoded HMAC-SHA256 i.e. sha256-XXXYYYZZZZ
            
            To compute HMAC-SHA256 concatenate
            - totp
            - currency
            - amount
            - cashier
            - terminal
            - location
            - trace
            - requestDate
            - requestTime
            - retry
            - sharedSecret
            
            then use SHA256 to produce the signature then prepend the string 'sha256-'
          
            given following values:
            
              - totp: 910112345678901200
              - currency: php
              - amount: 10123
              - cashier: jdelacruz
              - terminal: 16601
              - location: 166-columbia
              - trace: 166012359591
              - requestDate: 2018-10-01
              - requestTime: 23:59:59
              - retry: false
              - sharedSecret: a2c36905-c9bb-4ed2-9423-ec170e1eb6c1
            
            the computed signature is:
            sha256-783610D5A85295D355DD32CAA83277F313A5A00A7AD39CD8FC3AFBE03DF6EFC4
      required:  
        - totp
        - currency
        - amount
        - cashier
        - terminal
        - location
        - trace
        - requestDate
        - requestTime
        - retry
        - signature
  
  responses:
    InvalidParameters:
      description: |
        This result should be returned if any of the following is true:
        - the terminal is NOT valid
        - the location is NOT valid
        - the signature is NOT valid
        - the totp is NOT valid
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: 1
              message:
                type: string
                example: Invalid Parameters received
    DeductionFailed:
      description: |
        This result should be returned if any of the following is true:
        - balance deduction FAILED
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
                example: 11
              message:
                type: string
                example: Insufficient balance
      